FROM golang:1.20-alpine3.17 as builder

WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN go build -o bin/user-api ./cmd/user-api/main.go

FROM alpine:3.17

WORKDIR /app
COPY --from=builder /app/bin .
COPY --from=builder /app/configs/config.json /bin

EXPOSE 5000
ENTRYPOINT ["/app/bin/user-api"]